version: "3.3"
services:
  postgres:
    image: postgres:16
    container_name: garimpei_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: garimpeidb
    ports:
      - "7000:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - garimpei-api-net

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: garimpei_api_dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DATABASE=garimpeidb
    depends_on:
      - postgres
    networks:
      - garimpei-api-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: garimpei_pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - garimpei-api-net

volumes:
  pgdata_dev:

networks:
  garimpei-api-net:
    driver: bridge
